//
// Created by Michin on 21.04.2024.
//

#ifndef INC_2024__TAB_DSA__8_BRODZIAK_STATESCONF_HPP
#define INC_2024__TAB_DSA__8_BRODZIAK_STATESCONF_HPP

enum class States
{
    IDLE,
    LOGIN,
    REGISTER,
    MENU,
    PROMPT,
    FAVOURITES,
    TAGS,
    HISTORY,
    EXIT,
    RESULT,
    ABOUT,
    RESULTTAGS,
    LISTTAGS
};

#endif //INC_2024__TAB_DSA__8_BRODZIAK_STATESCONF_HPP
