//
// Created by Michin on 21.04.2024.
//

#ifndef INC_2024__TAB_DSA__8_BRODZIAK_STATEFAVOURITES_HPP
#define INC_2024__TAB_DSA__8_BRODZIAK_STATEFAVOURITES_HPP


class StateFavourites {

};


#endif //INC_2024__TAB_DSA__8_BRODZIAK_STATEFAVOURITES_HPP
